baseURL = 'https://securitykid.github.io/Blog/'
languageCode = 'en-us'
title = 'Koshary for the win!'
theme = 'hugo-theme-stack'

# Number of posts per page
[pagination]
  pagerSize = 5

# Code highlighting
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]
  description = "Personal blog of Yosif Qassim"
  rssFullContent = true

  [params.sidebar]
    emoji = "🎯"
    subtitle = "Personal blog of Yosif Qassim"

  [params.footer]
    since = 2025

  [params.article]
    math = false
    toc = true
    readingTime = true

  [params.colorScheme]
    toggle = true
    default = "auto"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/SecurityKid"
    weight = 4

[social]
  [social.github]
    identifier = "SecurityKid"

  [social.linkedin]
    identifier = "yosif-qassim"
