baseURL = 'https://securitykid.com'
locale = 'en-us'
title = 'Security Kid Blog'
theme = 'hugo-theme-stack'

defaultContentLanguage = 'en'
hasCJKLanguage = false

# Pagination
[pagination]
  pagerSize = 5

# Permalinks
[permalinks]
  post = "/posts/:slug/"
  page = "/:slug/"

# Code highlighting
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]
  description = "Personal blog of Yosif Qassim"
  rssFullContent = true

  [params.sidebar]
    emoji = "🧉"
    subtitle = "Personal blog of Yosif Qassim"
    avatar = "/img/avatar.png"

  [params.footer]
    since = 2025

  [params.article]
    math = false
    toc = true
    readingTime = true
    [params.article.list]
      showTags = true

  [params.colorScheme]
    toggle = true
    default = "auto"

  [params.widgets]
    homepage = [
      { type = "search" },
      { type = "archives", params = { limit = 5 } },
      { type = "categories", params = { limit = 10 } },
      { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [
      { type = "toc" }
    ]

# Social
[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/SecurityKid"
  weight = 1

  [menu.social.params]
    icon = "brand-github"

[[menu.social]]
  identifier = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/yosif-qassim/"
  weight = 2

  [menu.social.params]
    icon = "user"

# Menu
[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [menu.main.params]
    icon = "home"

[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 2

  [menu.main.params]
    icon = "archives"

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4

  [menu.main.params]
    icon = "user"
